insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (1, 'GM200', 'GeForce GTX Titan X');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (2, 'GM200', 'Nvidia Geforce GTX 980 Ti');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (3, 'Fiji', 'AMD Radeon R9 Fury X');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (4, 'Fiji', 'AMD Radeon R9 Fury');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (5, 'Fiji', 'AMD Radeon R9 Nano');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (6, 'GM204', 'Nvidia Geforce GTX 980');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (7, 'Hawaii', 'AMD Radeon R9 390X');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (8, 'GK110', 'Nvidia Geforce GTX Titan Black');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (9, 'GK110', 'Nvidia Geforce GTX 780 Ti');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (10, 'Hawaii', 'AMD Radeon R9 390');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (11, 'GM204', 'Nvidia Geforce GTX 970');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (12, 'GK110', 'Nvidia Geforce GTX Titan');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (13, 'Hawaii', 'AMD Radeon R9 290X');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (14, 'Hawaii', 'AMD Radeon R9 290');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (15, 'GK110', 'Nvidia Geforce GTX 780');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (16, 'R1000', 'AMD Radeon HD 7970 GHz');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (17, 'Tonga', 'AMD Radeon R9 380X');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (18, 'Tahiti', 'AMD Radeon R9 280X');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (19, 'GK104', 'Nvidia Geforce GTX 770');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (20, 'GK104', 'Nvidia Geforce GTX 680');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (21, 'R1000', 'AMD Radeon HD 7970');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (22, 'Tonga', 'AMD Radeon R9 380');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (23, 'GM206', 'Nvidia Geforce GTX 960');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (24, 'GK104', 'Nvidia Geforce GTX 670');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (25, 'R1000', 'AMD Radeon HD 7950 Boost');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (26, 'Tahiti', 'AMD Radeon R9 280');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (27, 'Tonga', 'AMD Radeon R9 285');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (28, 'R800', 'ATI Radeon HD 5970');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (29, 'GK104', 'Nvidia Geforce GTX 760');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (30, 'R1000', 'AMD Radeon HD 7950');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (31, 'Pitcairn', 'AMD Radeon R9 270X');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (32, 'GK104', 'Nvidia Geforce GTX 660 Ti');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (33, 'GF110', 'Nvidia Geforce GTX 580');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (34, 'Pitcairn', 'AMD Radeon HD 7870');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (35, 'Pitcairn', 'AMD Radeon R9 270');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (36, 'GK106', 'Nvidia Geforce GTX 660');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (37, 'GF110', 'Nvidia Geforce GTX 570');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (38, 'Curacao', 'AMD Radeon R7 265');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (39, 'Cayman', 'AMD Radeon HD 6970');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (40, 'GM206', 'Nvidia Geforce GTX 950');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (41, 'GF100', 'Nvidia Geforce GTX 480');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (42, 'GF110', 'Nvidia Geforce GTX 560 Ti 448 C');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (43, 'GK106', 'Nvidia Geforce GTX 650 Ti Boost');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (44, 'Pitcairn', 'AMD Radeon HD 7850');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (45, 'Cayman', 'AMD Radeon HD 6950');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (46, 'RV870', 'ATI Radeon HD 5870');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (47, 'GM107', 'Nvidia Geforce GTX 750 Ti');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (48, 'GF114', 'Nvidia Geforce GTX 560 Ti');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (49, 'Bonaire', 'AMD Radeon R7 260X');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (50, 'GF100', 'Nvidia Geforce GTX 470');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (51, '2x GT200b', 'Nvidia Geforce GTX 295');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (52, 'R700', 'ATI Radeon HD 4870 X2');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (53, 'GM107', 'Nvidia Geforce GTX 750');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (54, 'Barts', 'AMD Radeon HD 6870');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (55, 'Bonaire', 'AMD Radeon HD 7790');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (56, 'GF114', 'Nvidia Geforce GTX 560');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (57, 'Bonaire', 'AMD Radeon R7 260');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (58, 'RV870', 'ATI Radeon HD 5850');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (59, 'R700', 'ATI Radeon HD 4850 X2');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (60, 'GK106', 'Nvidia Geforce GTX 650 Ti');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (61, 'GF104', 'Nvidia Geforce GTX 460');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (62, 'Barts', 'AMD Radeon HD 6850');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (63, 'GF100', 'Nvidia Geforce GTX 465');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (64, 'GF104', 'Nvidia Geforce GTX 460');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (65, 'GT200b', 'Nvidia Geforce GTX 285');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (66, 'RV870', 'ATI Radeon HD 5830');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (67, 'Cape Verde', 'AMD Radeon HD 7770');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (68, 'GT200b', 'Nvidia Geforce GTX 275');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (69, 'GT200', 'Nvidia Geforce GTX 280');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (70, 'Barts', 'AMD Radeon HD 6790');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (71, 'RV790', 'ATI Radeon HD 4890');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (72, '2x G92', 'Nvidia Geforce 9800 GX2');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (73, 'GT200', 'Nvidia Geforce GTX 260 216');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (74, 'RV770', 'ATI Radeon HD 4870');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (75, 'GF116', 'Nvidia Geforce GTX 550 Ti');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (76, 'RV840', 'AMD Radeon HD 6770');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (77, 'RV840', 'ATI Radeon HD 5770');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (78, 'GK107', 'Nvidia Geforce GTX 650');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (79, 'GT200', 'Nvidia Geforce GTX 260');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (80, 'Cape Verde', 'AMD Radeon HD 7750');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (81, 'RV770', 'ATI Radeon HD 4870');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (82, 'R680', 'ATI Radeon HD 3870 X2');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (83, 'RV840', 'AMD Radeon HD 6750');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (84, 'RV840', 'ATI Radeon HD 5750');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (85, 'GF106', 'Nvidia Geforce GTS 450');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (86, 'G92b', 'Nvidia Geforce GTS 250');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (87, 'G92b', 'Nvidia Geforce 9800 GTX+');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (88, 'RV770', 'ATI Radeon HD 4850');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (89, 'G80', 'Nvidia Geforce 8800 Ultra');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (90, 'G92', 'Nvidia Geforce 9800 GTX');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (91, 'G80', 'Nvidia Geforce 8800 GTX');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (92, 'Oland', 'AMD Radeon R7 250');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (93, 'RV740', 'ATI Radeon HD 4770');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (94, 'G92', 'Nvidia Geforce 8800 GTS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (95, 'Turks', 'AMD Radeon HD 6670');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (96, 'GK107', 'Nvidia Geforce GT 640');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (97, 'Cap Verde', 'AMD Radeon HD 7730');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (98, 'RV770', 'ATI Radeon HD 4730');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (99, 'RV770', 'ATI Radeon HD 4830');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (100, 'G92', 'Nvidia Geforce 9800 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (101, 'G92', 'Nvidia Geforce 8800 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (102, 'RV830', 'ATI Radeon HD 5670');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (103, 'Turks', 'AMD Radeon HD 6570');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (104, 'Oland', 'AMD Radeon R7 240');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (105, 'RV670', 'ATI Radeon HD 3870');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (106, 'R600', 'ATI Radeon HD 2900 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (107, 'GF108', 'Nvidia Geforce GT 440');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (108, 'G94', 'Nvidia Geforce 9600 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (109, 'GT215', 'Nvidia Geforce GT 240');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (110, 'Oland', 'AMD Radeon R7 240');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (111, 'RV830', 'ATI Radeon HD 5570');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (112, 'RV730', 'ATI Radeon HD 4670');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (113, 'RV670', 'ATI Radeon HD 3850');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (114, 'G80', 'Nvidia Geforce 8800 GTS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (115, 'GF108', 'Nvidia Geforce GT 430');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (116, 'G92', 'Nvidia Geforce 9600 GSO');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (117, 'G92', 'Nvidia Geforce 8800 GS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (118, 'RV670', 'ATI Radeon HD 3850');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (119, 'R600', 'ATI Radeon HD 2900 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (120, 'G80', 'Nvidia Geforce 8800 GTS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (121, 'R580+', 'ATI Radeon X1950 XTX');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (122, 'R580', 'ATI Radeon X1900 XTX');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (123, 'R580+', 'ATI Radeon X1950 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (124, 'R580', 'ATI Radeon X1900 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (125, '2x G71', 'Nvidia Geforce 7950 GX2');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (126, 'R600', 'ATI Radeon HD 2900 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (127, 'G71', 'Nvidia Geforce 7900 GTX');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (128, 'G71', 'Nvidia Geforce 7900 GTO');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (129, 'G70', 'Nvidia Geforce 7800 GTX 512');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (130, 'G71', 'Nvidia Geforce 7950 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (131, 'R520', 'ATI Radeon X1800 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (132, 'RV570', 'ATI Radeon X1950 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (133, 'G96', 'Nvidia Geforce 9500 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (134, 'G84', 'Nvidia Geforce 8600 GTS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (135, 'G71', 'Nvidia Geforce 7900 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (136, 'RV630', 'ATI Radeon HD 2600 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (137, 'Caicos', 'ATI Radeon HD 6450');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (138, 'R580', 'ATI Radeon X1900 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (139, 'RV570', 'ATI Radeon X1950 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (140, 'RV635', 'ATI Radeon HD 3650');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (141, 'G70', 'Nvidia Geforce 7800 GTX');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (142, 'RV630', 'ATI Radeon HD 2600 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (143, 'G71', 'Nvidia Geforce 7900 GS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (144, 'G84', 'Nvidia Geforce 8600 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (145, 'G70', 'Nvidia Geforce 7800 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (146, 'R520', 'ATI Radeon X1800 XL');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (147, 'Caicos', 'ATI Radeon HD 6450');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (148, 'G70', 'Nvidia Geforce 7800 GS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (149, 'RV570', 'ATI Radeon X1650 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (150, 'R480', 'ATI Radeon X850 XT PE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (151, 'R420', 'ATI Radeon X800 XT PE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (152, 'RV630', 'ATI Radeon HD 2600 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (153, 'RV810', 'ATI Radeon HD 5450');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (154, 'RV710', 'ATI Radeon HD 4550');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (155, 'R520', 'ATI Radeon X1800 GTO');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (156, 'G73', 'Nvidia Geforce 7600 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (157, 'NV40', 'Nvidia Geforce 6800 Ultra');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (158, 'R480', 'ATI Radeon X850 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (159, 'R420', 'ATI Radeon X800 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (160, 'RV620', 'ATI Radeon HD 3470');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (161, 'NV40', 'Nvidia Geforce 6800 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (162, 'NV42', 'Nvidia Geforce 6800 GS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (163, 'R430', 'ATI Radeon X800 XL');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (164, 'R430', 'ATI Radeon X850 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (165, 'G96', 'Nvidia Geforce 9400 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (166, 'RV610', 'ATI Radeon HD 2400 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (167, 'R420', 'ATI Radeon X800 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (168, 'R430', 'ATI Radeon X800 GTO');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (169, 'RV535', 'ATI Radeon X1650 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (170, 'RV530', 'ATI Radeon X1600 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (171, 'G86', 'Nvidia Geforce 8500 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (172, 'G73', 'Nvidia Geforce 7600 GS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (173, 'NV40', 'Nvidia Geforce 6800');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (174, 'R420', 'ATI Radeon X800');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (175, 'R420', 'ATI Radeon X800 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (176, 'NV43', 'Nvidia Geforce 6600 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (177, 'R420', 'ATI Radeon X800 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (178, 'R420', 'ATI Radeon X800 SE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (179, 'NV40', 'Nvidia Geforce 6800 LE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (180, 'R360', 'ATI Radeon 9800 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (181, 'RV535', 'ATI Radeon X1600 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (182, 'RV530', 'ATI Radeon X1300 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (183, 'G73', 'Nvidia Geforce 7300 GT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (184, 'G98', 'Nvidia Geforce 8400 GS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (185, 'RV410', 'ATI Radeon X700 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (186, 'RV620', 'ATI Radeon HD 3450');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (187, 'RV410', 'ATI Radeon X700 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (188, 'RV610', 'ATI Radeon HD 2400 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (189, 'NV38', 'Nvidia Geforce FX 5950 Ultra');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (190, 'R350', 'ATI Radeon 9800 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (191, 'NV35', 'Nvidia Geforce FX 5900 Ultra');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (192, 'R350', 'ATI Radeon 9800 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (193, 'NV30', 'Nvidia Geforce FX 5800 Ultra');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (194, 'NV35', 'Nvidia Geforce FX 5900');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (195, 'RV410', 'ATI Radeon X700');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (196, 'RV515', 'ATI Radeon X1300 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (197, 'R300', 'ATI Radeon 9700 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (198, 'NV35', 'Nvidia Geforce FX 5900 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (199, 'RV516', 'ATI Radeon X1550');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (200, 'R350', 'ATI Radeon 9800');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (201, 'NV43', 'Nvidia Geforce 6600');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (202, 'NV30', 'Nvidia Geforce FX 5800');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (203, 'R300', 'ATI Radeon 9700');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (204, 'G72', 'Nvidia Geforce 7300 GS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (205, 'RV380', 'ATI Radeon X600 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (206, 'RV515', 'ATI Radeon X1300');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (207, 'NV36', 'Nvidia Geforce FX 5700 Ultra');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (208, 'R300', 'ATI Radeon 9500 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (209, 'RV360', 'ATI Radeon 9600 XT');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (210, 'G72', 'Nvidia Geforce 7200 GS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (211, 'R350', 'ATI Radeon 9800 SE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (212, 'G72', 'Nvidia Geforce 7300 LE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (213, 'NV43', 'Nvidia Geforce 6200');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (214, 'NV25', 'Nvidia Geforce 4 Ti 4600');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (215, 'NV36', 'Nvidia Geforce FX 5700');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (216, 'RV380', 'ATI Radeon X600 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (217, 'RV350', 'ATI Radeon 9600 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (218, 'NV25', 'Nvidia Geforce 4 Ti 4400');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (219, 'NV43', 'Nvidia Geforce 6600 LE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (220, 'NV31', 'Nvidia Geforce FX 5600 Ultra');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (221, 'RV370', 'ATI Radeon X550');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (222, 'NV25', 'Nvidia Geforce 4 Ti 4200');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (223, 'R300', 'ATI Radeon 9500');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (224, 'NV31', 'Nvidia Geforce FX 5600');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (225, 'NV34', 'Nvidia Geforce FX 5200 Ultra');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (226, 'NV36', 'Nvidia Geforce FX 5700 LE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (227, 'RV370', 'ATI Radeon X300');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (228, 'RV350', 'ATI Radeon 9600');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (229, 'NV20', 'Nvidia Geforce 3 Ti 500');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (230, 'R200', 'ATI Radeon 8500');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (231, 'R200', 'ATI Radeon 9100');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (232, 'R200', 'ATI Radeon 8500 LE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (233, 'RV350', 'ATI Radeon 9550');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (234, 'NV20', 'Nvidia Geforce 3');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (235, 'RV280', 'ATI Radeon 9200 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (236, 'RV250', 'ATI Radeon 9000 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (237, 'RV350', 'ATI Radeon 9600 SE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (238, 'NV34', 'Nvidia Geforce FX 5500');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (239, 'NV20', 'Nvidia Geforce 3 Ti 200');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (240, 'RV280', 'ATI Radeon 9200');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (241, 'NV34', 'Nvidia Geforce FX 5200');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (242, 'RV250', 'ATI Radeon 9000');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (243, 'RV280', 'ATI Radeon 9250');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (244, 'RV370', 'ATI Radeon X300 SE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (245, 'NV17', 'Nvidia Geforce 4 MX 460');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (246, 'NV15', 'Nvidia Geforce 2 Ti');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (247, 'NV17', 'Nvidia Geforce 4 MX 440');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (248, 'RV200', 'ATI Radeon 7500');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (249, 'RV280', 'ATI Radeon 9200 SE');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (250, 'NV15', 'Nvidia Geforce 2 Pro');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (251, 'NV15', 'Nvidia Geforce 2 GTS');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (252, 'NV17', 'Nvidia Geforce 4 MX 420');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (253, 'R100', 'ATI Radeon 7200');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (254, 'NV11', 'Nvidia Geforce 2 MX 400');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (255, 'RV100', 'ATI Radeon 7000');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (256, 'NV11', 'Nvidia Geforce 2 MX 200');
insert into tipo_tarjeta_video (tipo_tarjeta_video_id, clave, descripcion) values (257, 'GM200', 'GeForce GTX Titan X');
