insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (1, 'Actions ACT-ATM7029', 'Actions ACT-ATM7029');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (2, 'AllWinner A10', 'AllWinner A10');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (3, 'AllWinner A13', 'AllWinner A13');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (4, 'AMD A10 Micro-6700T', 'AMD A10 Micro-6700T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (5, 'AMD A10 Pro-7350B', 'AMD A10 Pro-7350B');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (6, 'AMD A10-4600M', 'AMD A10-4600M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (7, 'AMD A10-4655M', 'AMD A10-4655M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (8, 'AMD A10-4657M', 'AMD A10-4657M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (9, 'AMD A10-5745M', 'AMD A10-5745M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (10, 'AMD A10-5750M', 'AMD A10-5750M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (11, 'AMD A10-5757M', 'AMD A10-5757M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (12, 'AMD A10-5800K', 'AMD A10-5800K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (13, 'AMD A10-6800K', 'AMD A10-6800K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (14, 'AMD A10-7300', 'AMD A10-7300');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (15, 'AMD A10-7400P', 'AMD A10-7400P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (16, 'AMD A10-7700K', 'AMD A10-7700K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (17, 'AMD A10-7850K', 'AMD A10-7850K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (18, 'AMD A10-8700P', 'AMD A10-8700P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (19, 'AMD A10-9600P', 'AMD A10-9600P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (20, 'AMD A12-9700P', 'AMD A12-9700P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (21, 'AMD A4 Micro-6400T', 'AMD A4 Micro-6400T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (22, 'AMD A4-1200', 'AMD A4-1200');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (23, 'AMD A4-1250', 'AMD A4-1250');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (24, 'AMD A4-1350', 'AMD A4-1350');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (25, 'AMD A4-3300M', 'AMD A4-3300M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (26, 'AMD A4-3305M', 'AMD A4-3305M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (27, 'AMD A4-3310MX', 'AMD A4-3310MX');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (28, 'AMD A4-3320M', 'AMD A4-3320M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (29, 'AMD A4-3330MX', 'AMD A4-3330MX');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (30, 'AMD A4-4300M', 'AMD A4-4300M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (31, 'AMD A4-4355M', 'AMD A4-4355M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (32, 'AMD A4-5000', 'AMD A4-5000');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (33, 'AMD A4-5050', 'AMD A4-5050');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (34, 'AMD A4-5100', 'AMD A4-5100');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (35, 'AMD A4-5145M', 'AMD A4-5145M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (36, 'AMD A4-5150M', 'AMD A4-5150M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (37, 'AMD A4-5300', 'AMD A4-5300');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (38, 'AMD A4-6210', 'AMD A4-6210');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (39, 'AMD A4-7210', 'AMD A4-7210');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (40, 'AMD A6 Pro-7050B', 'AMD A6 Pro-7050B');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (41, 'AMD A6-1450', 'AMD A6-1450');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (42, 'AMD A6-3400M', 'AMD A6-3400M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (43, 'AMD A6-3410MX', 'AMD A6-3410MX');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (44, 'AMD A6-3420M', 'AMD A6-3420M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (45, 'AMD A6-3430MX', 'AMD A6-3430MX');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (46, 'AMD A6-4400M', 'AMD A6-4400M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (47, 'AMD A6-4455M', 'AMD A6-4455M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (48, 'AMD A6-5200', 'AMD A6-5200');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (49, 'AMD A6-5345M', 'AMD A6-5345M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (50, 'AMD A6-5350M', 'AMD A6-5350M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (51, 'AMD A6-5357M', 'AMD A6-5357M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (52, 'AMD A6-6310', 'AMD A6-6310');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (53, 'AMD A6-6400K', 'AMD A6-6400K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (54, 'AMD A6-7000', 'AMD A6-7000');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (55, 'AMD A6-7310', 'AMD A6-7310');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (56, 'AMD A6-8500P', 'AMD A6-8500P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (57, 'AMD A6-9210', 'AMD A6-9210');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (58, 'AMD A8 Pro-7150B', 'AMD A8 Pro-7150B');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (59, 'AMD A8-3500M', 'AMD A8-3500M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (60, 'AMD A8-3510MX', 'AMD A8-3510MX');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (61, 'AMD A8-3520M', 'AMD A8-3520M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (62, 'AMD A8-3530MX', 'AMD A8-3530MX');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (63, 'AMD A8-3550MX', 'AMD A8-3550MX');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (64, 'AMD A8-3850', 'AMD A8-3850');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (65, 'AMD A8-4500M', 'AMD A8-4500M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (66, 'AMD A8-4555M', 'AMD A8-4555M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (67, 'AMD A8-4557M', 'AMD A8-4557M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (68, 'AMD A8-5545M', 'AMD A8-5545M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (69, 'AMD A8-5550M', 'AMD A8-5550M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (70, 'AMD A8-5557M', 'AMD A8-5557M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (71, 'AMD A8-5600K', 'AMD A8-5600K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (72, 'AMD A8-6410', 'AMD A8-6410');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (73, 'AMD A8-6600K', 'AMD A8-6600K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (74, 'AMD A8-7100', 'AMD A8-7100');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (75, 'AMD A8-7200P', 'AMD A8-7200P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (76, 'AMD A8-7410', 'AMD A8-7410');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (77, 'AMD A8-7650K', 'AMD A8-7650K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (78, 'AMD A8-8600P', 'AMD A8-8600P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (79, 'AMD A9-9410', 'AMD A9-9410');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (80, 'AMD C-30', 'AMD C-30');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (81, 'AMD C-50', 'AMD C-50');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (82, 'AMD C-60', 'AMD C-60');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (83, 'AMD C-70', 'AMD C-70');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (84, 'AMD E1 Micro-6200T', 'AMD E1 Micro-6200T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (85, 'AMD E1-1200', 'AMD E1-1200');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (86, 'AMD E1-1500', 'AMD E1-1500');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (87, 'AMD E1-2100', 'AMD E1-2100');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (88, 'AMD E1-2200', 'AMD E1-2200');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (89, 'AMD E1-2500', 'AMD E1-2500');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (90, 'AMD E1-6010', 'AMD E1-6010');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (91, 'AMD E1-7010', 'AMD E1-7010');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (92, 'AMD E2-1800', 'AMD E2-1800');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (93, 'AMD E2-2000', 'AMD E2-2000');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (94, 'AMD E2-3000', 'AMD E2-3000');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (95, 'AMD E2-3000M', 'AMD E2-3000M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (96, 'AMD E2-3800', 'AMD E2-3800');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (97, 'AMD E-240', 'AMD E-240');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (98, 'AMD E2-6110', 'AMD E2-6110');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (99, 'AMD E2-7110', 'AMD E2-7110');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (100, 'AMD E2-9010', 'AMD E2-9010');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (101, 'AMD E-300', 'AMD E-300');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (102, 'AMD E-350', 'AMD E-350');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (103, 'AMD E-450', 'AMD E-450');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (104, 'AMD FX-7500', 'AMD FX-7500');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (105, 'AMD FX-7600P', 'AMD FX-7600P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (106, 'AMD FX-8350', 'AMD FX-8350');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (107, 'AMD FX-8800P', 'AMD FX-8800P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (108, 'AMD FX-9800P', 'AMD FX-9800P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (109, 'AMD FX-9830P', 'AMD FX-9830P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (110, 'AMD GX-210JA', 'AMD GX-210JA');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (111, 'AMD Pro A10-8700B', 'AMD Pro A10-8700B');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (112, 'AMD Pro A12-8800B', 'AMD Pro A12-8800B');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (113, 'AMD PRO A12-9800B', 'AMD PRO A12-9800B');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (114, 'AMD PRO A12-9830B', 'AMD PRO A12-9830B');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (115, 'AMD Pro A6-8500B', 'AMD Pro A6-8500B');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (116, 'AMD Pro A8-8600B', 'AMD Pro A8-8600B');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (117, 'AMD Ryzen 5 1400', 'AMD Ryzen 5 1400');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (118, 'AMD Ryzen 5 1600', 'AMD Ryzen 5 1600');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (119, 'AMD Ryzen 7 1700', 'AMD Ryzen 7 1700');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (120, 'AMD Ryzen 7 1700X', 'AMD Ryzen 7 1700X');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (121, 'AMD Ryzen 7 1800X', 'AMD Ryzen 7 1800X');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (122, 'AMD Z-01', 'AMD Z-01');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (123, 'AMD Z-60', 'AMD Z-60');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (124, 'Amlogic AML8726-MX', 'Amlogic AML8726-MX');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (125, 'Apple A10 Fusion', 'Apple A10 Fusion');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (126, 'Apple A4', 'Apple A4');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (127, 'Apple A5', 'Apple A5');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (128, 'Apple A5x', 'Apple A5x');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (129, 'Apple A6', 'Apple A6');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (130, 'Apple A6x', 'Apple A6x');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (131, 'Apple A7', 'Apple A7');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (132, 'Apple A8', 'Apple A8');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (133, 'Apple A8X', 'Apple A8X');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (134, 'Apple A9', 'Apple A9');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (135, 'Apple A9X', 'Apple A9X');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (136, 'ARM Cortex A8 1.2 GHz', 'ARM Cortex A8 1.2 GHz');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (137, 'ARM Cortex A8 1GHz', 'ARM Cortex A8 1GHz');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (138, 'Broadcom BCM21664T', 'Broadcom BCM21664T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (139, 'Broadcom BCM28155', 'Broadcom BCM28155');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (140, 'HiSilicon k3v2 Hi3620', 'HiSilicon k3v2 Hi3620');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (141, 'HiSilicon Kirin 620', 'HiSilicon Kirin 620');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (142, 'HiSilicon Kirin 650', 'HiSilicon Kirin 650');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (143, 'HiSilicon Kirin 655', 'HiSilicon Kirin 655');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (144, 'HiSilicon Kirin 658', 'HiSilicon Kirin 658');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (145, 'HiSilicon Kirin 910', 'HiSilicon Kirin 910');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (146, 'HiSilicon Kirin 910T', 'HiSilicon Kirin 910T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (147, 'HiSilicon Kirin 920', 'HiSilicon Kirin 920');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (148, 'HiSilicon Kirin 925', 'HiSilicon Kirin 925');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (149, 'HiSilicon Kirin 930', 'HiSilicon Kirin 930');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (150, 'HiSilicon Kirin 935', 'HiSilicon Kirin 935');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (151, 'HiSilicon Kirin 950', 'HiSilicon Kirin 950');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (152, 'HiSilicon Kirin 955', 'HiSilicon Kirin 955');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (153, 'HiSilicon Kirin 960', 'HiSilicon Kirin 960');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (154, 'Intel Atom D2550', 'Intel Atom D2550');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (155, 'Intel Atom D2560', 'Intel Atom D2560');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (156, 'Intel Atom D2700', 'Intel Atom D2700');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (157, 'Intel Atom E3805', 'Intel Atom E3805');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (158, 'Intel Atom E3815', 'Intel Atom E3815');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (159, 'Intel Atom E3825', 'Intel Atom E3825');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (160, 'Intel Atom E3826', 'Intel Atom E3826');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (161, 'Intel Atom E3827', 'Intel Atom E3827');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (162, 'Intel Atom E3845', 'Intel Atom E3845');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (163, 'Intel Atom N2600', 'Intel Atom N2600');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (164, 'Intel Atom N2650', 'Intel Atom N2650');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (165, 'Intel Atom N2800', 'Intel Atom N2800');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (166, 'Intel Atom N2850', 'Intel Atom N2850');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (167, 'Intel Atom x3-C3130', 'Intel Atom x3-C3130');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (168, 'Intel Atom x3-C3230RK', 'Intel Atom x3-C3230RK');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (169, 'Intel Atom x3-C3440', 'Intel Atom x3-C3440');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (170, 'Intel Atom x5-Z8300', 'Intel Atom x5-Z8300');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (171, 'Intel Atom x5-Z8350', 'Intel Atom x5-Z8350');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (172, 'Intel Atom x5-Z8500', 'Intel Atom x5-Z8500');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (173, 'Intel Atom x5-Z8550', 'Intel Atom x5-Z8550');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (174, 'Intel Atom x7-Z8700', 'Intel Atom x7-Z8700');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (175, 'Intel Atom x7-Z8750', 'Intel Atom x7-Z8750');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (176, 'Intel Atom Z2420', 'Intel Atom Z2420');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (177, 'Intel Atom Z2460', 'Intel Atom Z2460');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (178, 'Intel Atom Z2480', 'Intel Atom Z2480');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (179, 'Intel Atom Z2560', 'Intel Atom Z2560');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (180, 'Intel Atom Z2580', 'Intel Atom Z2580');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (181, 'Intel Atom Z2760', 'Intel Atom Z2760');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (182, 'Intel Atom Z3460', 'Intel Atom Z3460');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (183, 'Intel Atom Z3480', 'Intel Atom Z3480');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (184, 'Intel Atom Z3530', 'Intel Atom Z3530');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (185, 'Intel Atom Z3560', 'Intel Atom Z3560');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (186, 'Intel Atom Z3570', 'Intel Atom Z3570');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (187, 'Intel Atom Z3580', 'Intel Atom Z3580');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (188, 'Intel Atom Z3680', 'Intel Atom Z3680');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (189, 'Intel Atom Z3680D', 'Intel Atom Z3680D');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (190, 'Intel Atom Z3735D', 'Intel Atom Z3735D');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (191, 'Intel Atom Z3735E', 'Intel Atom Z3735E');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (192, 'Intel Atom Z3735F', 'Intel Atom Z3735F');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (193, 'Intel Atom Z3735G', 'Intel Atom Z3735G');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (194, 'Intel Atom Z3736F', 'Intel Atom Z3736F');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (195, 'Intel Atom Z3736G', 'Intel Atom Z3736G');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (196, 'Intel Atom Z3740', 'Intel Atom Z3740');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (197, 'Intel Atom Z3740D', 'Intel Atom Z3740D');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (198, 'Intel Atom Z3745', 'Intel Atom Z3745');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (199, 'Intel Atom Z3745D', 'Intel Atom Z3745D');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (200, 'Intel Atom Z3770', 'Intel Atom Z3770');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (201, 'Intel Atom Z3770D', 'Intel Atom Z3770D');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (202, 'Intel Atom Z3775', 'Intel Atom Z3775');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (203, 'Intel Atom Z3775D', 'Intel Atom Z3775D');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (204, 'Intel Atom Z3785', 'Intel Atom Z3785');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (205, 'Intel Atom Z3795', 'Intel Atom Z3795');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (206, 'Intel Celeron 1000M', 'Intel Celeron 1000M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (207, 'Intel Celeron 1005M', 'Intel Celeron 1005M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (208, 'Intel Celeron 1007U', 'Intel Celeron 1007U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (209, 'Intel Celeron 1017U', 'Intel Celeron 1017U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (210, 'Intel Celeron 1019Y', 'Intel Celeron 1019Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (211, 'Intel Celeron 1020E', 'Intel Celeron 1020E');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (212, 'Intel Celeron 1020M', 'Intel Celeron 1020M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (213, 'Intel Celeron 1037U', 'Intel Celeron 1037U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (214, 'Intel Celeron 1047UE', 'Intel Celeron 1047UE');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (215, 'Intel Celeron 2950M', 'Intel Celeron 2950M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (216, 'Intel Celeron 2955U', 'Intel Celeron 2955U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (217, 'Intel Celeron 2957U', 'Intel Celeron 2957U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (218, 'Intel Celeron 2961Y', 'Intel Celeron 2961Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (219, 'Intel Celeron 2970M', 'Intel Celeron 2970M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (220, 'Intel Celeron 2980U', 'Intel Celeron 2980U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (221, 'Intel Celeron 2981U', 'Intel Celeron 2981U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (222, 'Intel Celeron 3205U', 'Intel Celeron 3205U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (223, 'Intel Celeron 3215U', 'Intel Celeron 3215U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (224, 'Intel Celeron 3755U', 'Intel Celeron 3755U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (225, 'Intel Celeron 3765U', 'Intel Celeron 3765U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (226, 'Intel Celeron 797', 'Intel Celeron 797');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (227, 'Intel Celeron 807', 'Intel Celeron 807');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (228, 'Intel Celeron 847', 'Intel Celeron 847');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (229, 'Intel Celeron 867', 'Intel Celeron 867');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (230, 'Intel Celeron 877', 'Intel Celeron 877');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (231, 'Intel Celeron 887', 'Intel Celeron 887');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (232, 'Intel Celeron 927UE', 'Intel Celeron 927UE');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (233, 'Intel Celeron B710', 'Intel Celeron B710');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (234, 'Intel Celeron B720', 'Intel Celeron B720');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (235, 'Intel Celeron B730', 'Intel Celeron B730');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (236, 'Intel Celeron B800', 'Intel Celeron B800');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (237, 'Intel Celeron B810', 'Intel Celeron B810');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (238, 'Intel Celeron B815', 'Intel Celeron B815');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (239, 'Intel Celeron B820', 'Intel Celeron B820');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (240, 'Intel Celeron B830', 'Intel Celeron B830');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (241, 'Intel Celeron B840', 'Intel Celeron B840');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (242, 'Intel Celeron J1750', 'Intel Celeron J1750');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (243, 'Intel Celeron J1800', 'Intel Celeron J1800');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (244, 'Intel Celeron J1850', 'Intel Celeron J1850');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (245, 'Intel Celeron J1900', 'Intel Celeron J1900');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (246, 'Intel Celeron N2805', 'Intel Celeron N2805');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (247, 'Intel Celeron N2806', 'Intel Celeron N2806');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (248, 'Intel Celeron N2807', 'Intel Celeron N2807');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (249, 'Intel Celeron N2808', 'Intel Celeron N2808');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (250, 'Intel Celeron N2810', 'Intel Celeron N2810');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (251, 'Intel Celeron N2815', 'Intel Celeron N2815');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (252, 'Intel Celeron N2820', 'Intel Celeron N2820');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (253, 'Intel Celeron N2830', 'Intel Celeron N2830');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (254, 'Intel Celeron N2840', 'Intel Celeron N2840');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (255, 'Intel Celeron N2910', 'Intel Celeron N2910');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (256, 'Intel Celeron N2920', 'Intel Celeron N2920');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (257, 'Intel Celeron N2930', 'Intel Celeron N2930');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (258, 'Intel Celeron N2940', 'Intel Celeron N2940');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (259, 'Intel Celeron N3000', 'Intel Celeron N3000');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (260, 'Intel Celeron N3050', 'Intel Celeron N3050');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (261, 'Intel Celeron N3060', 'Intel Celeron N3060');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (262, 'Intel Celeron N3150', 'Intel Celeron N3150');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (263, 'Intel Celeron N3160', 'Intel Celeron N3160');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (264, 'Intel Celeron N3350', 'Intel Celeron N3350');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (265, 'Intel Celeron N3450', 'Intel Celeron N3450');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (266, 'Intel Core i3-2308M', 'Intel Core i3-2308M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (267, 'Intel Core i3-2310M', 'Intel Core i3-2310M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (268, 'Intel Core i3-2312M', 'Intel Core i3-2312M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (269, 'Intel Core i3-2328M', 'Intel Core i3-2328M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (270, 'Intel Core i3-2330M', 'Intel Core i3-2330M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (271, 'Intel Core i3-2348M', 'Intel Core i3-2348M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (272, 'Intel Core i3-2350M', 'Intel Core i3-2350M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (273, 'Intel Core i3-2357M', 'Intel Core i3-2357M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (274, 'Intel Core i3-2365M', 'Intel Core i3-2365M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (275, 'Intel Core i3-2367M', 'Intel Core i3-2367M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (276, 'Intel Core i3-2370M', 'Intel Core i3-2370M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (277, 'Intel Core i3-2375M', 'Intel Core i3-2375M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (278, 'Intel Core i3-2377M', 'Intel Core i3-2377M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (279, 'Intel Core i3-3110M', 'Intel Core i3-3110M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (280, 'Intel Core i3-3120M', 'Intel Core i3-3120M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (281, 'Intel Core i3-3130M', 'Intel Core i3-3130M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (282, 'Intel Core i3-3217U', 'Intel Core i3-3217U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (283, 'Intel Core i3-3220', 'Intel Core i3-3220');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (284, 'Intel Core i3-3227U', 'Intel Core i3-3227U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (285, 'Intel Core i3-3229Y', 'Intel Core i3-3229Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (286, 'Intel Core i3-4000M', 'Intel Core i3-4000M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (287, 'Intel Core i3-4005U', 'Intel Core i3-4005U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (288, 'Intel Core i3-4010U', 'Intel Core i3-4010U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (289, 'Intel Core i3-4010Y', 'Intel Core i3-4010Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (290, 'Intel Core i3-4012Y', 'Intel Core i3-4012Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (291, 'Intel Core i3-4020Y', 'Intel Core i3-4020Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (292, 'Intel Core i3-4025U', 'Intel Core i3-4025U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (293, 'Intel Core i3-4030U', 'Intel Core i3-4030U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (294, 'Intel Core i3-4030Y', 'Intel Core i3-4030Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (295, 'Intel Core i3-4100E', 'Intel Core i3-4100E');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (296, 'Intel Core i3-4100M', 'Intel Core i3-4100M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (297, 'Intel Core i3-4100U', 'Intel Core i3-4100U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (298, 'Intel Core i3-4102E', 'Intel Core i3-4102E');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (299, 'Intel Core i3-4110M', 'Intel Core i3-4110M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (300, 'Intel Core i3-4120U', 'Intel Core i3-4120U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (301, 'Intel Core i3-4158U', 'Intel Core i3-4158U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (302, 'Intel Core i3-5005U', 'Intel Core i3-5005U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (303, 'Intel Core i3-5010U', 'Intel Core i3-5010U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (304, 'Intel Core i3-5015U', 'Intel Core i3-5015U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (305, 'Intel Core i3-5020U', 'Intel Core i3-5020U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (306, 'Intel Core i3-5157U', 'Intel Core i3-5157U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (307, 'Intel Core i3-6006U', 'Intel Core i3-6006U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (308, 'Intel Core i3-6100H', 'Intel Core i3-6100H');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (309, 'Intel Core i3-6100U', 'Intel Core i3-6100U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (310, 'Intel Core i3-6157U', 'Intel Core i3-6157U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (311, 'Intel Core i3-6167U', 'Intel Core i3-6167U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (312, 'Intel Core i3-7100H', 'Intel Core i3-7100H');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (313, 'Intel Core i3-7100U', 'Intel Core i3-7100U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (314, 'Intel Core i3-7167U', 'Intel Core i3-7167U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (315, 'Intel Core i5-2400', 'Intel Core i5-2400');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (316, 'Intel Core i5-2410M', 'Intel Core i5-2410M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (317, 'Intel Core i5-2415M', 'Intel Core i5-2415M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (318, 'Intel Core i5-2430M', 'Intel Core i5-2430M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (319, 'Intel Core i5-2435M', 'Intel Core i5-2435M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (320, 'Intel Core i5-2450M', 'Intel Core i5-2450M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (321, 'Intel Core i5-2467M', 'Intel Core i5-2467M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (322, 'Intel Core i5-2500K', 'Intel Core i5-2500K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (323, 'Intel Core i5-2520M', 'Intel Core i5-2520M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (324, 'Intel Core i5-2537M', 'Intel Core i5-2537M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (325, 'Intel Core i5-2540M', 'Intel Core i5-2540M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (326, 'Intel Core i5-2557M', 'Intel Core i5-2557M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (327, 'Intel Core i5-3210M', 'Intel Core i5-3210M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (328, 'Intel Core i5-3230M', 'Intel Core i5-3230M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (329, 'Intel Core i5-3317U', 'Intel Core i5-3317U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (330, 'Intel Core i5-3320M', 'Intel Core i5-3320M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (331, 'Intel Core i5-3337U', 'Intel Core i5-3337U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (332, 'Intel Core i5-3339Y', 'Intel Core i5-3339Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (333, 'Intel Core i5-3340M', 'Intel Core i5-3340M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (334, 'Intel Core i5-3360M', 'Intel Core i5-3360M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (335, 'Intel Core i5-3380M', 'Intel Core i5-3380M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (336, 'Intel Core i5-3427U', 'Intel Core i5-3427U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (337, 'Intel Core i5-3437U', 'Intel Core i5-3437U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (338, 'Intel Core i5-3439Y', 'Intel Core i5-3439Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (339, 'Intel Core i5-3470', 'Intel Core i5-3470');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (340, 'Intel Core i5-3550', 'Intel Core i5-3550');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (341, 'Intel Core i5-3570K', 'Intel Core i5-3570K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (342, 'Intel Core i5-4200H', 'Intel Core i5-4200H');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (343, 'Intel Core i5-4200M', 'Intel Core i5-4200M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (344, 'Intel Core i5-4200U', 'Intel Core i5-4200U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (345, 'Intel Core i5-4200Y', 'Intel Core i5-4200Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (346, 'Intel Core i5-4202Y', 'Intel Core i5-4202Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (347, 'Intel Core i5-4210H', 'Intel Core i5-4210H');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (348, 'Intel Core i5-4210M', 'Intel Core i5-4210M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (349, 'Intel Core i5-4210U', 'Intel Core i5-4210U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (350, 'Intel Core i5-4210Y', 'Intel Core i5-4210Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (351, 'Intel Core i5-4220Y', 'Intel Core i5-4220Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (352, 'Intel Core i5-4250U', 'Intel Core i5-4250U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (353, 'Intel Core i5-4258U', 'Intel Core i5-4258U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (354, 'Intel Core i5-4260U', 'Intel Core i5-4260U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (355, 'Intel Core i5-4278U', 'Intel Core i5-4278U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (356, 'Intel Core i5-4288U', 'Intel Core i5-4288U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (357, 'Intel Core i5-4300M', 'Intel Core i5-4300M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (358, 'Intel Core i5-4300U', 'Intel Core i5-4300U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (359, 'Intel Core i5-4300Y', 'Intel Core i5-4300Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (360, 'Intel Core i5-4302Y', 'Intel Core i5-4302Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (361, 'Intel Core i5-4308U', 'Intel Core i5-4308U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (362, 'Intel Core i5-4310M', 'Intel Core i5-4310M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (363, 'Intel Core i5-4310U', 'Intel Core i5-4310U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (364, 'Intel Core i5-4330M', 'Intel Core i5-4330M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (365, 'Intel Core i5-4340M', 'Intel Core i5-4340M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (366, 'Intel Core i5-4350U', 'Intel Core i5-4350U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (367, 'Intel Core i5-4360U', 'Intel Core i5-4360U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (368, 'Intel Core i5-4400E', 'Intel Core i5-4400E');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (369, 'Intel Core i5-4402E', 'Intel Core i5-4402E');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (370, 'Intel Core i5-4430', 'Intel Core i5-4430');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (371, 'Intel Core i5-4460', 'Intel Core i5-4460');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (372, 'Intel Core i5-4590', 'Intel Core i5-4590');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (373, 'Intel Core i5-5200U', 'Intel Core i5-5200U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (374, 'Intel Core i5-5250U', 'Intel Core i5-5250U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (375, 'Intel Core i5-5257U', 'Intel Core i5-5257U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (376, 'Intel Core i5-5287U', 'Intel Core i5-5287U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (377, 'Intel Core i5-5300U', 'Intel Core i5-5300U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (378, 'Intel Core i5-5350H', 'Intel Core i5-5350H');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (379, 'Intel Core i5-5350U', 'Intel Core i5-5350U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (380, 'Intel Core i5-6198DU', 'Intel Core i5-6198DU');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (381, 'Intel Core i5-6200U', 'Intel Core i5-6200U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (382, 'Intel Core i5-6260U', 'Intel Core i5-6260U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (383, 'Intel Core i5-6267U', 'Intel Core i5-6267U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (384, 'Intel Core i5-6287U', 'Intel Core i5-6287U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (385, 'Intel Core i5-6300HQ', 'Intel Core i5-6300HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (386, 'Intel Core i5-6300U', 'Intel Core i5-6300U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (387, 'Intel Core i5-6350HQ', 'Intel Core i5-6350HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (388, 'Intel Core i5-6360U', 'Intel Core i5-6360U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (389, 'Intel Core i5-6400T', 'Intel Core i5-6400T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (390, 'Intel Core i5-6440HQ', 'Intel Core i5-6440HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (391, 'Intel Core i5-6500', 'Intel Core i5-6500');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (392, 'Intel Core i5-6500T', 'Intel Core i5-6500T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (393, 'Intel Core i5-6600K', 'Intel Core i5-6600K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (394, 'Intel Core i5-6600T', 'Intel Core i5-6600T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (395, 'Intel Core i5-7200U', 'Intel Core i5-7200U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (396, 'Intel Core i5-7260U', 'Intel Core i5-7260U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (397, 'Intel Core i5-7267U', 'Intel Core i5-7267U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (398, 'Intel Core i5-7287U', 'Intel Core i5-7287U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (399, 'Intel Core i5-7300HQ', 'Intel Core i5-7300HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (400, 'Intel Core i5-7300U', 'Intel Core i5-7300U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (401, 'Intel Core i5-7360U', 'Intel Core i5-7360U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (402, 'Intel Core i5-7440HQ', 'Intel Core i5-7440HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (403, 'Intel Core i5-7600K', 'Intel Core i5-7600K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (404, 'Intel Core i5-7Y54', 'Intel Core i5-7Y54');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (405, 'Intel Core i7-2600K', 'Intel Core i7-2600K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (406, 'Intel Core i7-2617M', 'Intel Core i7-2617M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (407, 'Intel Core i7-2620M', 'Intel Core i7-2620M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (408, 'Intel Core i7-2629M', 'Intel Core i7-2629M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (409, 'Intel Core i7-2630QM', 'Intel Core i7-2630QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (410, 'Intel Core i7-2635QM', 'Intel Core i7-2635QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (411, 'Intel Core i7-2637M', 'Intel Core i7-2637M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (412, 'Intel Core i7-2640M', 'Intel Core i7-2640M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (413, 'Intel Core i7-2649M', 'Intel Core i7-2649M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (414, 'Intel Core i7-2657M', 'Intel Core i7-2657M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (415, 'Intel Core i7-2670QM', 'Intel Core i7-2670QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (416, 'Intel Core i7-2675QM', 'Intel Core i7-2675QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (417, 'Intel Core i7-2677M', 'Intel Core i7-2677M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (418, 'Intel Core i7-2700K', 'Intel Core i7-2700K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (419, 'Intel Core i7-2720QM', 'Intel Core i7-2720QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (420, 'Intel Core i7-2760QM', 'Intel Core i7-2760QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (421, 'Intel Core i7-2820QM', 'Intel Core i7-2820QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (422, 'Intel Core i7-2860QM', 'Intel Core i7-2860QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (423, 'Intel Core i7-2920XM', 'Intel Core i7-2920XM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (424, 'Intel Core i7-2960XM', 'Intel Core i7-2960XM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (425, 'Intel Core i7-3517U', 'Intel Core i7-3517U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (426, 'Intel Core i7-3520M', 'Intel Core i7-3520M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (427, 'Intel Core i7-3537U', 'Intel Core i7-3537U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (428, 'Intel Core i7-3540M', 'Intel Core i7-3540M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (429, 'Intel Core i7-3610QM', 'Intel Core i7-3610QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (430, 'Intel Core i7-3612QM', 'Intel Core i7-3612QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (431, 'Intel Core i7-3615QM', 'Intel Core i7-3615QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (432, 'Intel Core i7-3630QM', 'Intel Core i7-3630QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (433, 'Intel Core i7-3632QM', 'Intel Core i7-3632QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (434, 'Intel Core i7-3635QM', 'Intel Core i7-3635QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (435, 'Intel Core i7-3667U', 'Intel Core i7-3667U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (436, 'Intel Core i7-3687U', 'Intel Core i7-3687U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (437, 'Intel Core i7-3689Y', 'Intel Core i7-3689Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (438, 'Intel Core i7-3720QM', 'Intel Core i7-3720QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (439, 'Intel Core i7-3740QM', 'Intel Core i7-3740QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (440, 'Intel Core i7-3770K', 'Intel Core i7-3770K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (441, 'Intel Core i7-3820QM', 'Intel Core i7-3820QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (442, 'Intel Core i7-3840QM', 'Intel Core i7-3840QM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (443, 'Intel Core i7-3920XM', 'Intel Core i7-3920XM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (444, 'Intel Core i7-3940XM', 'Intel Core i7-3940XM');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (445, 'Intel Core i7-3960X', 'Intel Core i7-3960X');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (446, 'Intel Core i7-4500U', 'Intel Core i7-4500U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (447, 'Intel Core i7-4510U', 'Intel Core i7-4510U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (448, 'Intel Core i7-4550U', 'Intel Core i7-4550U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (449, 'Intel Core i7-4558U', 'Intel Core i7-4558U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (450, 'Intel Core i7-4578U', 'Intel Core i7-4578U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (451, 'Intel Core i7-4600M', 'Intel Core i7-4600M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (452, 'Intel Core i7-4600U', 'Intel Core i7-4600U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (453, 'Intel Core i7-4610M', 'Intel Core i7-4610M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (454, 'Intel Core i7-4610Y', 'Intel Core i7-4610Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (455, 'Intel Core i7-4650U', 'Intel Core i7-4650U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (456, 'Intel Core i7-4700HQ', 'Intel Core i7-4700HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (457, 'Intel Core i7-4700MQ', 'Intel Core i7-4700MQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (458, 'Intel Core i7-4702HQ', 'Intel Core i7-4702HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (459, 'Intel Core i7-4702MQ', 'Intel Core i7-4702MQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (460, 'Intel Core i7-4710HQ', 'Intel Core i7-4710HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (461, 'Intel Core i7-4710MQ', 'Intel Core i7-4710MQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (462, 'Intel Core i7-4712HQ', 'Intel Core i7-4712HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (463, 'Intel Core i7-4712MQ', 'Intel Core i7-4712MQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (464, 'Intel Core i7-4720HQ', 'Intel Core i7-4720HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (465, 'Intel Core i7-4722HQ', 'Intel Core i7-4722HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (466, 'Intel Core i7-4750HQ', 'Intel Core i7-4750HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (467, 'Intel Core i7-4760HQ', 'Intel Core i7-4760HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (468, 'Intel Core i7-4770HQ', 'Intel Core i7-4770HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (469, 'Intel Core i7-4770K', 'Intel Core i7-4770K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (470, 'Intel Core i7-4790', 'Intel Core i7-4790');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (471, 'Intel Core i7-4790K', 'Intel Core i7-4790K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (472, 'Intel Core i7-4790S', 'Intel Core i7-4790S');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (473, 'Intel Core i7-4800MQ', 'Intel Core i7-4800MQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (474, 'Intel Core i7-4810MQ', 'Intel Core i7-4810MQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (475, 'Intel Core i7-4850HQ', 'Intel Core i7-4850HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (476, 'Intel Core i7-4860HQ', 'Intel Core i7-4860HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (477, 'Intel Core i7-4870HQ', 'Intel Core i7-4870HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (478, 'Intel Core i7-4900MQ', 'Intel Core i7-4900MQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (479, 'Intel Core i7-4910MQ', 'Intel Core i7-4910MQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (480, 'Intel Core i7-4930MX', 'Intel Core i7-4930MX');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (481, 'Intel Core i7-4940MX', 'Intel Core i7-4940MX');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (482, 'Intel Core i7-4950HQ', 'Intel Core i7-4950HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (483, 'Intel Core i7-4960HQ', 'Intel Core i7-4960HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (484, 'Intel Core i7-4960X', 'Intel Core i7-4960X');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (485, 'Intel Core i7-4980HQ', 'Intel Core i7-4980HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (486, 'Intel Core i7-5500U', 'Intel Core i7-5500U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (487, 'Intel Core i7-5550U', 'Intel Core i7-5550U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (488, 'Intel Core i7-5557U', 'Intel Core i7-5557U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (489, 'Intel Core i7-5600U', 'Intel Core i7-5600U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (490, 'Intel Core i7-5650U', 'Intel Core i7-5650U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (491, 'Intel Core i7-5700HQ', 'Intel Core i7-5700HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (492, 'Intel Core i7-5750HQ', 'Intel Core i7-5750HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (493, 'Intel Core i7-5775C', 'Intel Core i7-5775C');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (494, 'Intel Core i7-5850HQ', 'Intel Core i7-5850HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (495, 'Intel Core i7-5950HQ', 'Intel Core i7-5950HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (496, 'Intel Core i7-5960X', 'Intel Core i7-5960X');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (497, 'Intel Core i7-6500U', 'Intel Core i7-6500U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (498, 'Intel Core i7-6560U', 'Intel Core i7-6560U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (499, 'Intel Core i7-6567U', 'Intel Core i7-6567U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (500, 'Intel Core i7-6600U', 'Intel Core i7-6600U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (501, 'Intel Core i7-6650U', 'Intel Core i7-6650U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (502, 'Intel Core i7-6700', 'Intel Core i7-6700');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (503, 'Intel Core i7-6700HQ', 'Intel Core i7-6700HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (504, 'Intel Core i7-6700K', 'Intel Core i7-6700K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (505, 'Intel Core i7-6700T', 'Intel Core i7-6700T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (506, 'Intel Core i7-6770HQ', 'Intel Core i7-6770HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (507, 'Intel Core i7-6820HK', 'Intel Core i7-6820HK');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (508, 'Intel Core i7-6820HQ', 'Intel Core i7-6820HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (509, 'Intel Core i7-6870HQ', 'Intel Core i7-6870HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (510, 'Intel Core i7-6920HQ', 'Intel Core i7-6920HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (511, 'Intel Core i7-6950X', 'Intel Core i7-6950X');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (512, 'Intel Core i7-6970HQ', 'Intel Core i7-6970HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (513, 'Intel Core i7-7500U', 'Intel Core i7-7500U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (514, 'Intel Core i7-7560U', 'Intel Core i7-7560U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (515, 'Intel Core i7-7567U', 'Intel Core i7-7567U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (516, 'Intel Core i7-7600U', 'Intel Core i7-7600U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (517, 'Intel Core i7-7660U', 'Intel Core i7-7660U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (518, 'Intel Core i7-7700', 'Intel Core i7-7700');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (519, 'Intel Core i7-7700HQ', 'Intel Core i7-7700HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (520, 'Intel Core i7-7700K', 'Intel Core i7-7700K');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (521, 'Intel Core i7-7820HK', 'Intel Core i7-7820HK');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (522, 'Intel Core i7-7820HQ', 'Intel Core i7-7820HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (523, 'Intel Core i7-7920HQ', 'Intel Core i7-7920HQ');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (524, 'Intel Core i7-7Y75', 'Intel Core i7-7Y75');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (525, 'Intel Core m3-6Y30', 'Intel Core m3-6Y30');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (526, 'Intel Core m3-7Y30', 'Intel Core m3-7Y30');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (527, 'Intel Core m3-7Y32', 'Intel Core m3-7Y32');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (528, 'Intel Core m5-6Y54', 'Intel Core m5-6Y54');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (529, 'Intel Core m5-6Y57', 'Intel Core m5-6Y57');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (530, 'Intel Core M-5Y10', 'Intel Core M-5Y10');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (531, 'Intel Core M-5Y10a', 'Intel Core M-5Y10a');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (532, 'Intel Core M-5Y10c', 'Intel Core M-5Y10c');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (533, 'Intel Core M-5Y31', 'Intel Core M-5Y31');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (534, 'Intel Core M-5Y51', 'Intel Core M-5Y51');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (535, 'Intel Core M-5Y70', 'Intel Core M-5Y70');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (536, 'Intel Core M-5Y71', 'Intel Core M-5Y71');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (537, 'Intel Core m7-6Y75', 'Intel Core m7-6Y75');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (538, 'Intel Pentium 2020M', 'Intel Pentium 2020M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (539, 'Intel Pentium 2030M', 'Intel Pentium 2030M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (540, 'Intel Pentium 2117U', 'Intel Pentium 2117U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (541, 'Intel Pentium 2127U', 'Intel Pentium 2127U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (542, 'Intel Pentium 2129Y', 'Intel Pentium 2129Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (543, 'Intel Pentium 3550M', 'Intel Pentium 3550M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (544, 'Intel Pentium 3556U', 'Intel Pentium 3556U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (545, 'Intel Pentium 3558U', 'Intel Pentium 3558U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (546, 'Intel Pentium 3560M', 'Intel Pentium 3560M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (547, 'Intel Pentium 3560Y', 'Intel Pentium 3560Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (548, 'Intel Pentium 3561Y', 'Intel Pentium 3561Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (549, 'Intel Pentium 3805U', 'Intel Pentium 3805U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (550, 'Intel Pentium 3825U', 'Intel Pentium 3825U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (551, 'Intel Pentium 4405U', 'Intel Pentium 4405U');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (552, 'Intel Pentium 4405Y', 'Intel Pentium 4405Y');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (553, 'Intel Pentium 957', 'Intel Pentium 957');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (554, 'Intel Pentium 967', 'Intel Pentium 967');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (555, 'Intel Pentium 977', 'Intel Pentium 977');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (556, 'Intel Pentium 987', 'Intel Pentium 987');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (557, 'Intel Pentium 997', 'Intel Pentium 997');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (558, 'Intel Pentium B940', 'Intel Pentium B940');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (559, 'Intel Pentium B950', 'Intel Pentium B950');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (560, 'Intel Pentium B960', 'Intel Pentium B960');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (561, 'Intel Pentium B970', 'Intel Pentium B970');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (562, 'Intel Pentium B980', 'Intel Pentium B980');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (563, 'Intel Pentium G4500T', 'Intel Pentium G4500T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (564, 'Intel Pentium G860', 'Intel Pentium G860');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (565, 'Intel Pentium J2850', 'Intel Pentium J2850');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (566, 'Intel Pentium J2900', 'Intel Pentium J2900');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (567, 'Intel Pentium N3510', 'Intel Pentium N3510');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (568, 'Intel Pentium N3520', 'Intel Pentium N3520');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (569, 'Intel Pentium N3530', 'Intel Pentium N3530');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (570, 'Intel Pentium N3540', 'Intel Pentium N3540');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (571, 'Intel Pentium N3700', 'Intel Pentium N3700');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (572, 'Intel Pentium N3710', 'Intel Pentium N3710');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (573, 'Intel Pentium N4200', 'Intel Pentium N4200');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (574, 'Intel Xeon E3-1226 v3', 'Intel Xeon E3-1226 v3');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (575, 'Intel Xeon E3-1230 v3', 'Intel Xeon E3-1230 v3');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (576, 'Intel Xeon E3-1231 v3', 'Intel Xeon E3-1231 v3');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (577, 'Intel Xeon E3-1505M v5', 'Intel Xeon E3-1505M v5');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (578, 'Intel Xeon E3-1505M v6', 'Intel Xeon E3-1505M v6');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (579, 'Intel Xeon E3-1515M v5', 'Intel Xeon E3-1515M v5');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (580, 'Intel Xeon E3-1535M v5', 'Intel Xeon E3-1535M v5');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (581, 'Intel Xeon E3-1535M v6', 'Intel Xeon E3-1535M v6');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (582, 'Intel Xeon E3-1545M v5', 'Intel Xeon E3-1545M v5');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (583, 'Intel Xeon E3-1575M v5', 'Intel Xeon E3-1575M v5');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (584, 'Intel Xeon E5-2680', 'Intel Xeon E5-2680');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (585, 'Intel Xeon E5-2680 v4', 'Intel Xeon E5-2680 v4');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (586, 'Intel Xeon E5-2697 v2', 'Intel Xeon E5-2697 v2');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (587, 'Loongson 2F 900MHz', 'Loongson 2F 900MHz');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (588, 'Marvell Armada PXA1908', 'Marvell Armada PXA1908');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (589, 'Marvell PXA1088', 'Marvell PXA1088');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (590, 'Marvell PXA986', 'Marvell PXA986');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (591, 'Mediatek Helio P10 MT6755', 'Mediatek Helio P10 MT6755');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (592, 'Mediatek Helio P20 (LP4) MT6757', 'Mediatek Helio P20 (LP4) MT6757');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (593, 'Mediatek Helio X10 MT6795', 'Mediatek Helio X10 MT6795');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (594, 'Mediatek Helio X20 MT6797', 'Mediatek Helio X20 MT6797');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (595, 'MediaTek MT6572', 'MediaTek MT6572');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (596, 'MediaTek MT6575', 'MediaTek MT6575');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (597, 'MediaTek MT6577', 'MediaTek MT6577');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (598, 'Mediatek MT6580M', 'Mediatek MT6580M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (599, 'Mediatek MT6582', 'Mediatek MT6582');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (600, 'Mediatek MT6582M', 'Mediatek MT6582M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (601, 'Mediatek MT6589', 'Mediatek MT6589');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (602, 'Mediatek MT6589T', 'Mediatek MT6589T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (603, 'Mediatek MT6592', 'Mediatek MT6592');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (604, 'Mediatek MT6595', 'Mediatek MT6595');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (605, 'Mediatek MT6595 Turbo', 'Mediatek MT6595 Turbo');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (606, 'Mediatek MT6595M', 'Mediatek MT6595M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (607, 'Mediatek MT6732', 'Mediatek MT6732');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (608, 'Mediatek MT6735', 'Mediatek MT6735');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (609, 'Mediatek MT6735M', 'Mediatek MT6735M');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (610, 'Mediatek MT6735P', 'Mediatek MT6735P');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (611, 'Mediatek MT6737', 'Mediatek MT6737');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (612, 'Mediatek MT6737T', 'Mediatek MT6737T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (613, 'Mediatek MT6750', 'Mediatek MT6750');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (614, 'Mediatek MT6752', 'Mediatek MT6752');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (615, 'Mediatek MT6753', 'Mediatek MT6753');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (616, 'Mediatek MT8121', 'Mediatek MT8121');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (617, 'Mediatek MT8125', 'Mediatek MT8125');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (618, 'Mediatek MT8127', 'Mediatek MT8127');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (619, 'Mediatek MT8135', 'Mediatek MT8135');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (620, 'MediaTek MT8161', 'MediaTek MT8161');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (621, 'MediaTek MT8163 V/A 1.5 GHz', 'MediaTek MT8163 V/A 1.5 GHz');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (622, 'MediaTek MT8163 V/B 1.3 GHz', 'MediaTek MT8163 V/B 1.3 GHz');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (623, 'Mediatek MT8165', 'Mediatek MT8165');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (624, 'Mediatek MT8173', 'Mediatek MT8173');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (625, 'Mediatek MT8173C', 'Mediatek MT8173C');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (626, 'Mediatek MT8176', 'Mediatek MT8176');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (627, 'MediaTek MT8312', 'MediaTek MT8312');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (628, 'MediaTek MT8317T', 'MediaTek MT8317T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (629, 'MediaTek MT8377', 'MediaTek MT8377');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (630, 'Mediatek MT8389', 'Mediatek MT8389');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (631, 'Mediatek MT8732', 'Mediatek MT8732');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (632, 'Mediatek MT8735', 'Mediatek MT8735');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (633, 'Mediatek MT8752', 'Mediatek MT8752');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (634, 'Nvidia Tegra 2 (250)', 'Nvidia Tegra 2 (250)');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (635, 'NVIDIA Tegra 3', 'NVIDIA Tegra 3');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (636, 'Nvidia Tegra 4', 'Nvidia Tegra 4');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (637, 'Nvidia Tegra K1', 'Nvidia Tegra K1');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (638, 'Nvidia Tegra K1 (Denver)', 'Nvidia Tegra K1 (Denver)');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (639, 'Nvidia Tegra X1', 'Nvidia Tegra X1');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (640, 'Qualcomm 205', 'Qualcomm 205');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (641, 'Qualcomm Snapdragon 200 8210', 'Qualcomm Snapdragon 200 8210');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (642, 'Qualcomm Snapdragon 200 8225Q', 'Qualcomm Snapdragon 200 8225Q');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (643, 'Qualcomm Snapdragon 200 MSM8212', 'Qualcomm Snapdragon 200 MSM8212');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (644, 'Qualcomm Snapdragon 210 MSM8909', 'Qualcomm Snapdragon 210 MSM8909');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (645, 'Qualcomm Snapdragon 212 APQ8009', 'Qualcomm Snapdragon 212 APQ8009');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (646, 'Qualcomm Snapdragon 400 8930AB', 'Qualcomm Snapdragon 400 8930AB');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (647, 'Qualcomm Snapdragon 400 APQ8026', 'Qualcomm Snapdragon 400 APQ8026');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (648, 'Qualcomm Snapdragon 400 APQ8028', 'Qualcomm Snapdragon 400 APQ8028');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (649, 'Qualcomm Snapdragon 400 MSM8226', 'Qualcomm Snapdragon 400 MSM8226');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (650, 'Qualcomm Snapdragon 400 MSM8926', 'Qualcomm Snapdragon 400 MSM8926');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (651, 'Qualcomm Snapdragon 400 MSM8928', 'Qualcomm Snapdragon 400 MSM8928');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (652, 'Qualcomm Snapdragon 410 APQ8016', 'Qualcomm Snapdragon 410 APQ8016');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (653, 'Qualcomm Snapdragon 410 MSM8916', 'Qualcomm Snapdragon 410 MSM8916');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (654, 'Qualcomm Snapdragon 415 MSM8929', 'Qualcomm Snapdragon 415 MSM8929');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (655, 'Qualcomm Snapdragon 425', 'Qualcomm Snapdragon 425');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (656, 'Qualcomm Snapdragon 430', 'Qualcomm Snapdragon 430');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (657, 'Qualcomm Snapdragon 435', 'Qualcomm Snapdragon 435');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (658, 'Qualcomm Snapdragon 600 APQ8064T', 'Qualcomm Snapdragon 600 APQ8064T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (659, 'Qualcomm Snapdragon 610 MSM8936', 'Qualcomm Snapdragon 610 MSM8936');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (660, 'Qualcomm Snapdragon 615 MSM8939', 'Qualcomm Snapdragon 615 MSM8939');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (661, 'Qualcomm Snapdragon 616 MSM8939v2', 'Qualcomm Snapdragon 616 MSM8939v2');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (662, 'Qualcomm Snapdragon 617 MSM8952', 'Qualcomm Snapdragon 617 MSM8952');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (663, 'Qualcomm Snapdragon 625', 'Qualcomm Snapdragon 625');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (664, 'Qualcomm Snapdragon 650 MSM8956', 'Qualcomm Snapdragon 650 MSM8956');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (665, 'Qualcomm Snapdragon 652 MSM8976', 'Qualcomm Snapdragon 652 MSM8976');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (666, 'Qualcomm Snapdragon 800 MSM8974', 'Qualcomm Snapdragon 800 MSM8974');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (667, 'Qualcomm Snapdragon 801 APQ8074AB', 'Qualcomm Snapdragon 801 APQ8074AB');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (668, 'Qualcomm Snapdragon 801 MSM8974AA', 'Qualcomm Snapdragon 801 MSM8974AA');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (669, 'Qualcomm Snapdragon 801 MSM8974AB', 'Qualcomm Snapdragon 801 MSM8974AB');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (670, 'Qualcomm Snapdragon 801 MSM8974AC', 'Qualcomm Snapdragon 801 MSM8974AC');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (671, 'Qualcomm Snapdragon 805 APQ8084', 'Qualcomm Snapdragon 805 APQ8084');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (672, 'Qualcomm Snapdragon 808 MSM8992', 'Qualcomm Snapdragon 808 MSM8992');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (673, 'Qualcomm Snapdragon 810 MSM8994', 'Qualcomm Snapdragon 810 MSM8994');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (674, 'Qualcomm Snapdragon 820 MSM8996', 'Qualcomm Snapdragon 820 MSM8996');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (675, 'Qualcomm Snapdragon 821 MSM8996 Pro', 'Qualcomm Snapdragon 821 MSM8996 Pro');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (676, 'Qualcomm Snapdragon 835 (8998)', 'Qualcomm Snapdragon 835 (8998)');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (677, 'Qualcomm Snapdragon S1 MSM7225A', 'Qualcomm Snapdragon S1 MSM7225A');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (678, 'Qualcomm Snapdragon S1 MSM7227', 'Qualcomm Snapdragon S1 MSM7227');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (679, 'Qualcomm Snapdragon S1 MSM7227A', 'Qualcomm Snapdragon S1 MSM7227A');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (680, 'Qualcomm Snapdragon S1 QSD8250', 'Qualcomm Snapdragon S1 QSD8250');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (681, 'Qualcomm Snapdragon S2 MSM8255', 'Qualcomm Snapdragon S2 MSM8255');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (682, 'Qualcomm Snapdragon S3 MSM8260', 'Qualcomm Snapdragon S3 MSM8260');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (683, 'Qualcomm Snapdragon S3 MSM8660', 'Qualcomm Snapdragon S3 MSM8660');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (684, 'Qualcomm Snapdragon S4 Play MSM8225', 'Qualcomm Snapdragon S4 Play MSM8225');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (685, 'Qualcomm Snapdragon S4 Play MSM8225Q', 'Qualcomm Snapdragon S4 Play MSM8225Q');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (686, 'Qualcomm Snapdragon S4 Play MSM8625Q', 'Qualcomm Snapdragon S4 Play MSM8625Q');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (687, 'Qualcomm Snapdragon S4 Plus APQ8060A', 'Qualcomm Snapdragon S4 Plus APQ8060A');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (688, 'Qualcomm Snapdragon S4 Plus MSM8227', 'Qualcomm Snapdragon S4 Plus MSM8227');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (689, 'Qualcomm Snapdragon S4 Plus MSM8230', 'Qualcomm Snapdragon S4 Plus MSM8230');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (690, 'Qualcomm Snapdragon S4 Plus MSM8260A', 'Qualcomm Snapdragon S4 Plus MSM8260A');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (691, 'Qualcomm Snapdragon S4 Plus MSM8930', 'Qualcomm Snapdragon S4 Plus MSM8930');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (692, 'Qualcomm Snapdragon S4 Plus MSM8960', 'Qualcomm Snapdragon S4 Plus MSM8960');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (693, 'Qualcomm Snapdragon S4 Pro APQ8064A', 'Qualcomm Snapdragon S4 Pro APQ8064A');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (694, 'Qualcomm Snapdragon S4 Pro MSM8960DT', 'Qualcomm Snapdragon S4 Pro MSM8960DT');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (695, 'Qualcomm Snapdragon S4 Pro MSM8960T', 'Qualcomm Snapdragon S4 Pro MSM8960T');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (696, 'Renesas MP5232', 'Renesas MP5232');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (697, 'Rockchip RK2918', 'Rockchip RK2918');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (698, 'Rockchip RK2918 1.2 GHz', 'Rockchip RK2918 1.2 GHz');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (699, 'Rockchip RK3066 1.5 GHz', 'Rockchip RK3066 1.5 GHz');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (700, 'Rockchip RK3168', 'Rockchip RK3168');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (701, 'Rockchip RK3188', 'Rockchip RK3188');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (702, 'Rockchip RK3288', 'Rockchip RK3288');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (703, 'Samsung Exynos 3470 Quad', 'Samsung Exynos 3470 Quad');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (704, 'Samsung Exynos 3475 Quad', 'Samsung Exynos 3475 Quad');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (705, 'Samsung Exynos 4210 1.2 GHz', 'Samsung Exynos 4210 1.2 GHz');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (706, 'Samsung Exynos 4210 1.4 GHz', 'Samsung Exynos 4210 1.4 GHz');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (707, 'Samsung Exynos 4212 1.5 GHz', 'Samsung Exynos 4212 1.5 GHz');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (708, 'Samsung Exynos 4412 Quad', 'Samsung Exynos 4412 Quad');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (709, 'Samsung Exynos 5250 Dual', 'Samsung Exynos 5250 Dual');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (710, 'Samsung Exynos 5260 Hexa', 'Samsung Exynos 5260 Hexa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (711, 'Samsung Exynos 5410 Octa', 'Samsung Exynos 5410 Octa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (712, 'Samsung Exynos 5410 Octa', 'Samsung Exynos 5410 Octa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (713, 'Samsung Exynos 5420 Octa', 'Samsung Exynos 5420 Octa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (714, 'Samsung Exynos 5430 Octa', 'Samsung Exynos 5430 Octa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (715, 'Samsung Exynos 5433 Octa', 'Samsung Exynos 5433 Octa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (716, 'Samsung Exynos 7420 Octa', 'Samsung Exynos 7420 Octa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (717, 'Samsung Exynos 7578', 'Samsung Exynos 7578');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (718, 'Samsung Exynos 7580 Octa', 'Samsung Exynos 7580 Octa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (719, 'Samsung Exynos 7870 Octa', 'Samsung Exynos 7870 Octa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (720, 'Samsung Exynos 7880', 'Samsung Exynos 7880');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (721, 'Samsung Exynos 8890 Octa', 'Samsung Exynos 8890 Octa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (722, 'Samsung Exynos 8895 Octa', 'Samsung Exynos 8895 Octa');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (723, 'Samsung Hummingbird S5PC110/Exynos 3110', 'Samsung Hummingbird S5PC110/Exynos 3110');
insert into tipo_procesador (tipo_procesador_id, clave, descripcion) values (724, 'Spreadtrum SC7731', 'Spreadtrum SC7731');
